basePath: '{{.BasePath}}'
definitions:
  entity.Event:
    properties:
      description:
        type: string
      image:
        type: string
      name:
        type: string
    type: object
  entity.Plan:
    properties:
      description:
        type: string
      events:
        items:
          $ref: '#/definitions/entity.Event'
        type: array
      image:
        type: string
      name:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /api/v1/plan:
    get:
      parameters:
      - description: offset
        in: query
        name: offset
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Plan'
            type: array
      tags:
      - Plan
swagger: "2.0"
